### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by imbrian** [OnBelayApp/hr-alumni#5]
/api/board Router

GET /posts (get all posts and categories)
POST /post/create (new post)
GET /post/read/:id (post content)
GET /post/replies/:id (all replies)
POST /post/replies/:id (create reply)
GET /category/:category (get individual category)
PUT /post/read/:id/upvote (upvote a post)
PUT /post/replies/:id/thumb (thumb up a reply)

**Comment by rlin415** [comment]
resolves
